# Generated by Django 3.2 on 2021-07-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_data_database',
            name='ventor_id',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
