# Generated by Django 3.2 on 2021-07-22 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_device_data_database_ventor_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vehicledetails',
            table='vehicleDetails',
        ),
    ]
