# Generated by Django 3.2.4 on 2021-07-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210730_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.BigIntegerField(default=10),
        ),
    ]
