# Generated by Django 3.2 on 2021-07-22 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_vehicledetails_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='live_location_table',
            table='live_location_table',
        ),
    ]
