# Generated by Django 3.2.4 on 2021-07-24 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210724_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_vehicle_services',
            name='driver_mobile',
            field=models.CharField(blank=True, help_text='Phone number without Country Code', max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
