# Generated by Django 3.2.4 on 2021-07-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_vehicle_services_driver_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_vehicle_services',
            name='renewal_of_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_vehicle_services',
            name='renewal_of_fitness',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_vehicle_services',
            name='renewal_of_insurance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_vehicle_services',
            name='renewal_of_pollution',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_vehicle_services',
            name='renewal_of_tax',
            field=models.DateField(blank=True, null=True),
        ),
    ]
